services:
  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_psd
      - db_root_psd
      - my_cred
    networks:
      - custom
    volumes:
      - /home/inicoara/data:/var/lib/mysql

networks:
  custom:
    driver: bridge
secrets:
  my_cred:
    file: ../secrets/credentials.txt
  db_psd:
    file: ../secrets/db_password.txt
  db_root_psd:
    file: ../secrets/db_root_password.txt

